[colors]
comparison_colors = [
    {r = 8, g = 34, b = 34},
    {r = 10, g = 195, b = 124},
    {r = 170, g = 0, b = 50},
    {r = 5, g = 215, b = 0},
    {r = 0, g = 0, b = 139},
    {r = 0, g = 20, b = 60},
    {r = 9, g = 0, b = 139},
    {r = 0, g = 255, b = 127},
]